# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: nextfoxos
description: Sistema operativo personalizado basado en Fedora con herramientas para desarrollo y gaming.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  # 1. Aplicaciones Flatpak por defecto (forzando la v1 compatible)
  - type: default-flatpaks@v1
    notify: true
    system:
      repo: flathub
      install:
        # Navegador y Herramientas de Desarrollo
        - com.brave.Browser
        - com.visualstudio.code
        - org.godotengine.Godot

        # Plataformas de Gaming y Launchers de PC
        - com.valvesoftware.Steam               
        - com.heroicgameslauncher.hgl
        - net.lutris.Lutris
        - org.prismlauncher.PrismLauncher       
        
        # Emulación y Herramientas Útiles
        - org.duckstation.DuckStation           
        - net.pcsx2.PCSX2
        - org.ppsspp.PPSSPP

  # 2. Registrar tu script de personalización desde su ruta real
  - type: script
    scripts:
      - ../files/scripts/personalizar.sh
