# recipes/recipe.yml
name: nextfoxos
description: Custom operating system based on Fedora Atomic. Focused on gamers who want to play without many background processes.

# Base estable de Fedora Kinoite (KDE Plasma)
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40

modules:
  # 1. Copiar archivos personalizados del repositorio al sistema
  - type: files

  # 2. Configurar los repositorios de paquetes de RPM Fusion (drivers y códecs)
  - type: rpm-fusion

  # 3. Aplicaciones Flatpak por defecto instaladas en el sistema
  - type: default-flatpaks
    system:
      # Navegador y Herramientas de Desarrollo
      - com.brave.Browser
      - com.visualstudio.code
      - org.godotengine.Godot

      # Plataformas de Gaming y Launchers de PC
      - com.valvesoftware.Steam               
      - com.heroicgameslauncher.hgl
      - net.lutris.Lutris
      - org.prismlauncher.PrismLauncher       
      
      # Emulación y Herramientas Útiles
      - org.duckstation.DuckStation           
      - net.pcsx2.PCSX2
      - org.ppsspp.PPSSPP

  # 4. Registrar tu script personalizado de la terminal
  - type: script
    snippets:
      - personalizar.sh
